internal enum Enum1
{
	TRICKLE_ACTION_NONE,
	TRICKLE_ACTION_BUSY,
	TRICKLE_ACTION_TOWN_PORTAL,
	TRICKLE_ACTION_BOUNTY,
	TRICKLE_ACTION_DUNGEON_FINDER,
	TRICKLE_ACTION_IN_TOWN,
	TRICKLE_ACTION_IN_BOSS_FIGHT,
	TRICKLE_ACTION_IN_COMBAT
}
