internal enum Enum0
{
	TRICKLE_FLAG_DEAD_BIT,
	TRICKLE_FLAG_OBSERVER_BIT,
	TRICKLE_FLAG_NOT_ON_MAP,
	TRICKLE_FLAG_HIDDEN,
	TRICKLE_FLAG_BECOMES_ARROW,
	TRICKLE_FLAG_RESPECTS_FOW,
	TRICKLE_FLAG_PVP_PLAYER_REVEALED_ON_MAP,
	TRICKLE_FLAG_GHOSTED_BIT,
	TRICKLE_FLAG_HUNTER,
	TRICKLE_FLAG_LOOT_RUN_BOSS,
	TRICKLE_FLAG_COUNT
}
