namespace Plugins;

public enum ItemLocation
{
	Floor = -1,
	Inventory = 0,
	Head = 1,
	Torso = 2,
	RightHand = 3,
	LeftHand = 4,
	Hands = 5,
	Waist = 6,
	Feet = 7,
	Shoulders = 8,
	Legs = 9,
	Bracers = 10,
	LeftRing = 11,
	RightRing = 12,
	Neck = 13,
	MerchantBuyback = 14,
	Stash = 15,
	Gold = 16,
	MerchantAvaibleItemsForPurchase = 17,
	Merchant = 18,
	PtrVendor = 19,
	InSocket = 20,
	PetRightHand = 21,
	PetLeftHand = 22,
	PetSpecial = 23,
	PetNeck = 24,
	PetRightRing = 25,
	PetLeftRing = 26,
	PetHead = 27,
	PetTorso = 28,
	PetHands = 29,
	PetWaist = 30,
	PetFeet = 31,
	PetShoulders = 32,
	PetLegs = 33,
	PetBracers = 34,
	VendorToken = 1000
}
